// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nghmvumdtbijhhhksfrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naG12dW1kdGJpamhoaGtzZnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODM4MDgsImV4cCI6MjA2NTU1OTgwOH0.Xmm4vSqYx0D_zncK3JRhJn5Vxtzzafq9Mc1zoJwN5dE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);